In [113]:
from keras.models import load_model

model_save_path = 'C:/Users/KangDongha/Desktop/sign/model_trained_data.h5' #모델 파일의 경로
model = load_model(model_save_path) #모델 로드

In [2]:
import shutil

try:
    shutil.move('C:/Users/KangDongha/Desktop/U_turn.png', 'C:/Users/KangDongha/Desktop/sign') #현재위치, 타겟위치
except:
    pass

In [3]:
import os

FileName_G_E = 'G_E'
os.makedirs('C:/Users/KangDongha/Desktop/sign' + f'\\{FileName_G_E}')

FileExistsError: [WinError 183] 파일이 이미 있으므로 만들 수 없습니다: 'C:/Users/KangDongha/Desktop/sign\\G_E'

In [1]:
U_img = 'C:/Users/KangDongha/Desktop/sign'
print(U_img)

C:/Users/KangDongha/Desktop/sign


In [6]:
from keras.preprocessing import image

U_img_path = os.path.join(U_img, 'U_turn.PNG') #파일 경로, 파일 이름

U_img_load = image.load_img(U_img_path)

In [95]:
print(U_img_load)

<PIL.Image.Image image mode=RGB size=254x190 at 0x242BB2E9F40>


In [7]:
#이미지 타입 확인
U_img_np = image.img_to_array(U_img_load)

print(type(U_img_np))

<class 'numpy.ndarray'>


In [9]:
#이미지 파일 저장
import cv2
import numpy as np

#cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn2.PNG', U_img_np)
cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/1.PNG', U_img_np)

True

In [98]:
#이미지 그레이스케일
U_img_Gray = cv2.cvtColor(U_img_np,cv2.COLOR_BGR2GRAY)
cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn3.PNG', U_img_Gray)

True

In [14]:
"""사진 해상도 변경 및 확인
U_img_Equ = cv2.resize(U_img_np,(64,64))
cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn4-1.PNG', U_img_Equ)
U_img_path2 = os.path.join('C:/Users/KangDongha/Desktop', 'U_turn4-1.PNG')
U_img_load2 = image.load_img(U_img_path2)
print(U_img_load2)
"""

"사진 해상도 변경 및 확인\nU_img_Equ = cv2.resize(U_img_np,(64,64))\ncv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn4-1.PNG', U_img_Equ)\nU_img_path2 = os.path.join('C:/Users/KangDongha/Desktop', 'U_turn4-1.PNG')\nU_img_load2 = image.load_img(U_img_path2)\nprint(U_img_load2)\n"

In [15]:
#이미지 리드 후 이퀄라이징
U_img_Equ = cv2.imread(U_img_path, 0)
print(type(U_img_Equ))
print(U_img_Equ)
print(U_img_Equ.shape)
print(type(U_img_Equ.shape[0]))
U_img_Equ = cv2.equalizeHist(U_img_Equ)
cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn4.PNG', U_img_Equ)

<class 'numpy.ndarray'>
[[ 42  43  44 ...  11  12  13]
 [ 43  43  43 ...  15  15  15]
 [ 44  43  43 ...  13  12  11]
 ...
 [142 147 152 ... 168 166 165]
 [145 149 153 ... 168 167 166]
 [146 149 153 ... 167 167 167]]
(372, 580)
<class 'int'>


True

In [101]:
#그레이스케일 후 이퀄라이징
U_img_path_Gray = os.path.join('C:/Users/KangDongha/Desktop/sign/G_E', 'U_turn3.PNG')
U_img_Equ = cv2.imread(U_img_path_Gray, 0)
U_img_Equ = cv2.equalizeHist(U_img_Equ)
cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn6.PNG', U_img_Equ)

True

In [89]:
#U_img_Gray = cv2.resize(U_img_Gray, (32, 32))
#U_img_Gray = U_img_Gray.reshape(1, 32, 32, 1)

In [54]:
#cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn5.PNG', U_img_Gray)

True

In [102]:
U_img_Equ = cv2.resize(U_img_Equ, (32, 32))
cv2.imwrite('C:/Users/KangDongha/Desktop/sign/G_E/U_turn7.PNG', U_img_Equ)

U_img_Equ = U_img_Equ.reshape(1, 32, 32, 1)

In [110]:
def predict_class(Pred):
    if(classIndex == 0):
        print('No Right Turn')
    elif(classIndex == 1):
        print('Speed Bump')
    elif(classIndex == 2):
        print('U Turn')

In [111]:
predictions = model.predict(U_img_Equ) 
classIndex = model.predict_classes(U_img_Equ)
probabilityValue = np.amax(predictions)
print(probabilityValue) #적중률
print(len(predictions))
print(classIndex) #클래스
print(len(U_img_Equ))
predict_class(U_img_Equ)

1.0
1
[2]
1
U Turn


In [112]:
#이미지 전처리 위 과정 요약
"""
이미지 로드

np 형식

그레이 스케일

이퀄라이징


U_img = 'C:/Users/KangDongha/Desktop/sign'
U_img_path = os.path.join(U_img, 'U2.PNG') #파일 경로, 파일 이름
U_img_load = image.load_img(U_img_path)

U_img_np = image.img_to_array(U_img_load)

U_img_Equ = cv2.imread(U_img_path, 0)
U_img_Equ = cv2.equalizeHist(U_img_Equ)

U_img_Equ = cv2.resize(U_img_Equ, (32, 32))
U_img_Equ = U_img_Equ.reshape(1, 32, 32, 1)
"""

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/KangDongha/Desktop/sign\\U2.PNG'

In [ ]:
#예측
"""
a = model.predict(U_img_Equ)
print(a)
"""